name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo apt-get update && sudo apt-get install nodejs -y && sudo cd ./app && sudo npm install && sudo npm run build && sudo docker login -u sheerazzulfi -p Zulfi5171* && sudo docker build . --file ./app/Dockerfile --tag sheerazzulfi/samplenode && sudo docker push sheerazzulfi/samplenode
