name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo apt-get update && sudo apt-get install nodejs -y && cd ./app && npm install && npm run build && docker login -u sheerazzulfi -p Zulfi5171* && docker build . --file ./Dockerfile --tag sheerazzulfi/samplenode && docker push sheerazzulfi/samplenode
